// Arcaea iOS 7.0.256 address overrides; see docs/version-adaptation.md.
// Verified against source executable SHA-256 eae2722958eac2f7358d97a3a7e172726a59577fa15b98d70d747f7815d3e613.
#pragma once

#undef XRC_BRK_TIMING_INPUT_SITE_OFF
#define XRC_BRK_TIMING_INPUT_SITE_OFF (0x921120ULL)
#undef XRC_BRK_TIMING_ARC_INPUT_SITE_OFF
#define XRC_BRK_TIMING_ARC_INPUT_SITE_OFF (0x921DACULL)
#undef XRC_BRK_FLOW_UI_SITE_OFF
#define XRC_BRK_FLOW_UI_SITE_OFF (0x17A8D8ULL)
#undef XRC_BRK_TIMING_INPUT_REPLAY_OFF
#define XRC_BRK_TIMING_INPUT_REPLAY_OFF (0x146C170ULL)
#undef XRC_BRK_TIMING_ARC_INPUT_REPLAY_OFF
#define XRC_BRK_TIMING_ARC_INPUT_REPLAY_OFF (0x146C178ULL)
#undef XRC_BRK_FLOW_UI_REPLAY_OFF
#define XRC_BRK_FLOW_UI_REPLAY_OFF (0x146C180ULL)
#undef XRC_OFF_FLOW_SETTER
#define XRC_OFF_FLOW_SETTER (0xBD7904ULL)

#undef XRC_OFF_GP_VTABLE
#define XRC_OFF_GP_VTABLE (0x1521DC0ULL)
#undef XRC_OFF_GP_UPDATE_FN
#define XRC_OFF_GP_UPDATE_FN (0xCAA7C0ULL)
#undef XRC_JUDGE_STUB_ENTRY_OFF
#define XRC_JUDGE_STUB_ENTRY_OFF (0x920788ULL)
#undef XRC_OFF_JUDGE_COMMIT_FN
#define XRC_OFF_JUDGE_COMMIT_FN (0xACDFA8ULL)
#undef XRC_OFF_JUDGE_COMMIT_LN_FN
#define XRC_OFF_JUDGE_COMMIT_LN_FN (0xACDDCCULL)
#undef XRC_STUB_TRAMP_OFF
#define XRC_STUB_TRAMP_OFF (0x146C00CULL)
#undef XRC_JUDGE_SLOT_OFF
#define XRC_JUDGE_SLOT_OFF (0x164EF28ULL)
#undef XRC_INFO_OFF
#define XRC_INFO_OFF (0x164EF40ULL)
#undef XRC_OFF_MTP_VTABLE
#define XRC_OFF_MTP_VTABLE (0x14BB930ULL)
#undef XRC_OFF_MTP_GETPOS
#define XRC_OFF_MTP_GETPOS (0x8E4274ULL)
#undef XRC_OFF_CH_GET_POSITION
#define XRC_OFF_CH_GET_POSITION (0x1036D1CULL)
#undef XRC_OFF_GET_CURRENT_SOUND
#define XRC_OFF_GET_CURRENT_SOUND (0x10372BCULL)
#undef XRC_OFF_FMOD_CC_SET_PITCH
#define XRC_OFF_FMOD_CC_SET_PITCH (0x10E6458ULL)
#undef XRC_OFF_FMOD_CC_ADD_DSP
#define XRC_OFF_FMOD_CC_ADD_DSP (0x10E82F4ULL)
#undef XRC_OFF_FMOD_CREATE_DSP_BY_TYPE
#define XRC_OFF_FMOD_CREATE_DSP_BY_TYPE (0x10AEBC4ULL)
#undef XRC_OFF_FMOD_DSP_SET_PARAM_FLOAT
#define XRC_OFF_FMOD_DSP_SET_PARAM_FLOAT (0x1066ED4ULL)
#undef XRC_OFF_FMOD_DSP_GET_PARAM_FLOAT
#define XRC_OFF_FMOD_DSP_GET_PARAM_FLOAT (0x1067370ULL)
#undef XRC_OFF_FMOD_DSP_GET_INFO
#define XRC_OFF_FMOD_DSP_GET_INFO (0x1067DD0ULL)
#undef XRC_OFF_FMOD_DSP_RELEASE
#define XRC_OFF_FMOD_DSP_RELEASE (0x10657B8ULL)
#undef XRC_OFF_CH_SET_POSITION
#define XRC_OFF_CH_SET_POSITION (0x1036BF4ULL)
#undef XRC_OFF_FMOD_SYSTEM_GLOBAL
#define XRC_OFF_FMOD_SYSTEM_GLOBAL (0x1652A78ULL)
#undef XRC_BRK_APPLOG_SITE_OFF
#define XRC_BRK_APPLOG_SITE_OFF (0x6257DCULL)
#undef XRC_BRK_APPLOG_REPLAY_OFF
#define XRC_BRK_APPLOG_REPLAY_OFF (0x146C040ULL)
#undef XRC_BRK_APPLOG_BLOB_SITE_OFF
#define XRC_BRK_APPLOG_BLOB_SITE_OFF (0x63B6D4ULL)
#undef XRC_BRK_APPLOG_BLOB_REPLAY_OFF
#define XRC_BRK_APPLOG_BLOB_REPLAY_OFF (0x146C050ULL)
#undef XRC_BRK_UNLOCK_L1_SITE_OFF
#define XRC_BRK_UNLOCK_L1_SITE_OFF (0xBE70BCULL)
#undef XRC_BRK_UNLOCK_L1_REPLAY_OFF
#define XRC_BRK_UNLOCK_L1_REPLAY_OFF (0x146C058ULL)
#undef XRC_BRK_UNLOCK_L2_SITE_OFF
#define XRC_BRK_UNLOCK_L2_SITE_OFF (0xBE70FCULL)
#undef XRC_BRK_UNLOCK_L2_REPLAY_OFF
#define XRC_BRK_UNLOCK_L2_REPLAY_OFF (0x146C060ULL)
#undef XRC_BRK_UNLOCK_L3_SITE_OFF
#define XRC_BRK_UNLOCK_L3_SITE_OFF (0xBE7748ULL)
#undef XRC_BRK_UNLOCK_L3_REPLAY_OFF
#define XRC_BRK_UNLOCK_L3_REPLAY_OFF (0x146C068ULL)
#undef XRC_BRK_CB_READY_SITE_OFF
#define XRC_BRK_CB_READY_SITE_OFF (0xF463D4ULL)
#undef XRC_BRK_CB_READY_REPLAY_OFF
#define XRC_BRK_CB_READY_REPLAY_OFF (0x146C078ULL)
#undef XRC_BRK_CB_FILEHASH_SITE_OFF
#define XRC_BRK_CB_FILEHASH_SITE_OFF (0xF480FCULL)
#undef XRC_BRK_CB_FILEHASH_TARGET_OFF
#define XRC_BRK_CB_FILEHASH_TARGET_OFF (0xF48320ULL)
#undef XRC_BRK_CB_LISTHASH_SITE_OFF
#define XRC_BRK_CB_LISTHASH_SITE_OFF (0xF48210ULL)
#undef XRC_BRK_CB_LISTHASH_TARGET_OFF
#define XRC_BRK_CB_LISTHASH_TARGET_OFF (0xF48334ULL)
#undef XRC_BRK_CB_WIPE_SITE_OFF
#define XRC_BRK_CB_WIPE_SITE_OFF (0xF46D68ULL)
#undef XRC_BRK_CB_WIPE_REPLAY_OFF
#define XRC_BRK_CB_WIPE_REPLAY_OFF (0x146C120ULL)
#undef XRC_BRK_CB_DISPATCH_SITE_OFF
#define XRC_BRK_CB_DISPATCH_SITE_OFF (0x13E2A4ULL)
#undef XRC_BRK_CB_DISPATCH_REPLAY_OFF
#define XRC_BRK_CB_DISPATCH_REPLAY_OFF (0x146C088ULL)
#undef XRC_RESTORE_CB_VERIFY_SITE_OFF
#define XRC_RESTORE_CB_VERIFY_SITE_OFF (0xF4715CULL)
#undef XRC_BRK_AP_LN_STATE_SITE_OFF
#define XRC_BRK_AP_LN_STATE_SITE_OFF (0x91FCCCULL)
#undef XRC_BRK_AP_LN_TICK_SITE_OFF
#define XRC_BRK_AP_LN_TICK_SITE_OFF (0x91FD4CULL)
#undef XRC_BRK_AP_NOTE_WIN_SITE_OFF
#define XRC_BRK_AP_NOTE_WIN_SITE_OFF (0x91FE74ULL)
#undef XRC_BRK_AP_ARCTAP_WIN_SITE_OFF
#define XRC_BRK_AP_ARCTAP_WIN_SITE_OFF (0x920038ULL)
#undef XRC_BRK_AP_SWALLOW_JUDGE_SITE_OFF
#define XRC_BRK_AP_SWALLOW_JUDGE_SITE_OFF (0x920CCCULL)
#undef XRC_BRK_AP_SWALLOW_BATCH_SITE_OFF
#define XRC_BRK_AP_SWALLOW_BATCH_SITE_OFF (0x92178CULL)
#undef XRC_BRK_AP_SWALLOW_TOUCH_SITE_OFF
#define XRC_BRK_AP_SWALLOW_TOUCH_SITE_OFF (0x923EC8ULL)
#undef XRC_BRK_AP_ARC_VISUAL_SITE_OFF
#define XRC_BRK_AP_ARC_VISUAL_SITE_OFF (0x91ED88ULL)
#undef XRC_BRK_AP_LN_STATE_REPLAY_OFF
#define XRC_BRK_AP_LN_STATE_REPLAY_OFF (0x146C0B0ULL)
#undef XRC_BRK_AP_LN_TICK_REPLAY_OFF
#define XRC_BRK_AP_LN_TICK_REPLAY_OFF (0x146C0B8ULL)
#undef XRC_BRK_AP_NOTE_WIN_REPLAY_OFF
#define XRC_BRK_AP_NOTE_WIN_REPLAY_OFF (0x146C0C0ULL)
#undef XRC_BRK_AP_ARCTAP_WIN_REPLAY_OFF
#define XRC_BRK_AP_ARCTAP_WIN_REPLAY_OFF (0x146C0C8ULL)
#undef XRC_BRK_AP_SWALLOW_JUDGE_REPLAY_OFF
#define XRC_BRK_AP_SWALLOW_JUDGE_REPLAY_OFF (0x146C0D0ULL)
#undef XRC_BRK_AP_SWALLOW_BATCH_REPLAY_OFF
#define XRC_BRK_AP_SWALLOW_BATCH_REPLAY_OFF (0x146C0D8ULL)
#undef XRC_BRK_AP_SWALLOW_TOUCH_REPLAY_OFF
#define XRC_BRK_AP_SWALLOW_TOUCH_REPLAY_OFF (0x146C0E0ULL)
#undef XRC_BRK_AP_ARC_VISUAL_REPLAY_OFF
#define XRC_BRK_AP_ARC_VISUAL_REPLAY_OFF (0x146C0E8ULL)
#undef XRC_BRK_AP_TICKCNT1_SITE_OFF
#define XRC_BRK_AP_TICKCNT1_SITE_OFF (0x91FDC0ULL)
#undef XRC_BRK_AP_TICKCNT2_SITE_OFF
#define XRC_BRK_AP_TICKCNT2_SITE_OFF (0x91FEC0ULL)
#undef XRC_BRK_AP_TICKCNT1_REPLAY_OFF
#define XRC_BRK_AP_TICKCNT1_REPLAY_OFF (0x146C0F0ULL)
#undef XRC_BRK_AP_TICKCNT2_REPLAY_OFF
#define XRC_BRK_AP_TICKCNT2_REPLAY_OFF (0x146C0F8ULL)
#undef XRC_BRK_LOCK_FV_SITE_OFF
#define XRC_BRK_LOCK_FV_SITE_OFF (0x993668ULL)
#undef XRC_BRK_LOCK_FV_REPLAY_OFF
#define XRC_BRK_LOCK_FV_REPLAY_OFF (0x146C100ULL)
#undef XRC_BRK_LOCK_DO_SITE_OFF
#define XRC_BRK_LOCK_DO_SITE_OFF (0xAB0958ULL)
#undef XRC_BRK_LOCK_DO_REPLAY_OFF
#define XRC_BRK_LOCK_DO_REPLAY_OFF (0x146C108ULL)
#undef XRC_BRK_FV_GATE_SITE_OFF
#define XRC_BRK_FV_GATE_SITE_OFF (0x9936CCULL)
#undef XRC_BRK_FV_GATE_REPLAY_OFF
#define XRC_BRK_FV_GATE_REPLAY_OFF (0x146C110ULL)
#undef XRC_BRK_CHAIN_PROG_SITE_OFF
#define XRC_BRK_CHAIN_PROG_SITE_OFF (0x991C7CULL)
#undef XRC_BRK_CHAIN_PROG_REPLAY_OFF
#define XRC_BRK_CHAIN_PROG_REPLAY_OFF (0x146C118ULL)
#undef XRC_BRK_RPF_DRAW_SITE_OFF
#define XRC_BRK_RPF_DRAW_SITE_OFF (0xB25E0CULL)
#undef XRC_BRK_RPF_ARCTICK_SITE_OFF
#define XRC_BRK_RPF_ARCTICK_SITE_OFF (0xB0233CULL)
#undef XRC_BRK_RPF_ARCPASS_SITE_OFF
#define XRC_BRK_RPF_ARCPASS_SITE_OFF (0xB021BCULL)
#undef XRC_BRK_ARC_HIDE_A_SITE_OFF
#define XRC_BRK_ARC_HIDE_A_SITE_OFF (0xB02288ULL)
#undef XRC_BRK_ARC_HIDE_B_SITE_OFF
#define XRC_BRK_ARC_HIDE_B_SITE_OFF (0xB025A8ULL)
#undef XRC_LN_VPTR_ARC
#define XRC_LN_VPTR_ARC (0x14A03A0ULL)
#undef XRC_LN_VPTR_HOLD
#define XRC_LN_VPTR_HOLD (0x14BBD00ULL)
#undef XRC_AP_NOTE_WIN_CONT_OFF
#define XRC_AP_NOTE_WIN_CONT_OFF (0x91FE48ULL)
#undef XRC_AP_ARCTAP_WIN_CONT_OFF
#define XRC_AP_ARCTAP_WIN_CONT_OFF (0x91FE48ULL)
#undef XRC_OFF_FN_MARK_HOLD
#define XRC_OFF_FN_MARK_HOLD (0x8E65E8ULL)
#undef XRC_OFF_FN_ARC_SPRITE
#define XRC_OFF_FN_ARC_SPRITE (0x18936CULL)
#undef XRC_OFF_FN_ARC_CONSUME
#define XRC_OFF_FN_ARC_CONSUME (0x189374ULL)
#undef XRC_OM_VTABLE_OFF
#define XRC_OM_VTABLE_OFF (0x14A0490ULL)
#undef XRC_OFF_REPLAY_SET_BUCKET
#define XRC_OFF_REPLAY_SET_BUCKET (0x915770ULL)
#undef XRC_OFF_REPLAY_REGISTER_NOTE
#define XRC_OFF_REPLAY_REGISTER_NOTE (0x91D7D0ULL)
#undef XRC_OFF_APP_GLOBAL
#define XRC_OFF_APP_GLOBAL (0x16781D8ULL)
#undef XRC_OFF_REPLAY_REBUILD_ARC
#define XRC_OFF_REPLAY_REBUILD_ARC (0xB25128ULL)
#undef XRC_OFF_REPLAY_DRAW_LINE
#define XRC_OFF_REPLAY_DRAW_LINE (0xAE6684ULL)
#undef XRC_OFF_DL_STATE_READY_FN
#define XRC_OFF_DL_STATE_READY_FN (0x8464C8ULL)

#undef XRC_OFF_NODE_SCALE_Z
#define XRC_OFF_NODE_SCALE_Z (0xE6ECB0ULL)
#undef XRC_OFF_RENDER_ROOT_VPTR
#define XRC_OFF_RENDER_ROOT_VPTR (0x14F1EE8ULL)
#undef XRC_BRK_ADAPT_WINDOW_SITE_OFF
#define XRC_BRK_ADAPT_WINDOW_SITE_OFF (0x91E620ULL)
#undef XRC_BRK_ADAPT_WINDOW_REPLAY_OFF
#define XRC_BRK_ADAPT_WINDOW_REPLAY_OFF (0x146C1B8ULL)
